config:
  time-unit: minute
  modules:
    productivity: productivity-module-3
bus-inputs:
  accumulator: 2700
  advanced-circuit: 2700
  battery: 2700
  coal: 2700
  concrete: 2700
  copper-plate: 2700
  effectivity-module-3: 2700
  electric-engine-unit: 2700
  electric-motor: 2700
  electronic-circuit: 2700
  explosive-cannon-shell: 2700
  explosives: 2700
  express-splitter: 2700
  express-transport-belt: 2700
  express-underground-belt: 2700
  fast-inserter: 2700
  flying-robot-frame: 2700
  glass: 2700
  iron-plate: 2700
  landfill: 2700
  low-density-structure: 2700
  plastic-bar: 2700
  processing-unit: 2700
  productivity-module-3: 2700
  radar: 2700
  refined-concrete: 2700
  rocket-control-unit: 2700
  rocket-fuel: 2700
  se-aeroframe-pole: 2700
  se-aeroframe-scaffold: 2700
  se-beryllium-plate: 2700
  se-canister: 2700
  se-heat-shielding: 2700
  se-heavy-girder: 2700
  se-holmium-cable: 2700
  se-holmium-solenoid: 2700
  se-water-ice: 2700
  solar-panel: 2700
  solid-fuel: 2700
  speed-module-3: 2700
  steel-plate: 2700
  stone: 2700
  stone-brick: 2700
  sulfur: 2700
  uranium-235: 2700
  uranium-238: 2700
  se-iridium-plate: 2700
  heavy-oil: 36000
base-outputs:
  se-adaptive-armour-equipment-4: 0.001
  landfill: 200
  steam-turbine: 0.375
  heat-pipe: 10
  equipment-gantry: 0.5
  nuclear-fuel: 2
  equipment-gantry-remover: 0.5
  se-fluid-burner-generator: 0.5
  aai-storehouse-buffer: 0.1
  se-medpack-2: 0.5
  textplate-large-plastic: 1
  artillery-wagon: 0.1
  se-spaceship-ion-booster-tank: 0.5
  textplate-large-gold: 1
  se-rocket-landing-pad: 0.05
  se-lifesupport-equipment-1: 0.1
  stack-filter-inserter: 1
  textplate-large-steel: 1
  aai-warehouse-passive-provider: 0.1
  textplate-small-concrete: 1
  iron-chest: 8
  aai-strongbox: 1
  aai-storehouse-requester: 0.5
  aai-storehouse-storage: 0.5
  steel-chest: 5
  aai-warehouse: 0.1
  hazard-concrete: 100
  logistic-chest-buffer: 1
  textplate-large-stone: 1
  logistic-chest-active-provider: 1
  textplate-small-uranium: 1
  refined-hazard-concrete: 100
  textplate-large-iron: 1
  textplate-large-concrete: 1
  textplate-small-stone: 1
  aai-strongbox-passive-provider: 1
  aai-storehouse: 0.5
  aai-warehouse-buffer: 0.02
  textplate-small-copper: 1
  aai-strongbox-storage: 1
  aai-storehouse-passive-provider: 0.5
  textplate-large-uranium: 1
  refined-concrete: 100
  logistic-chest-requester: 5
  textplate-large-copper: 1
  aai-strongbox-requester: 1
  se-delivery-cannon-chest: 1
  aai-strongbox-buffer: 0.2
  textplate-small-glass: 1
  aai-strongbox-active-provider: 0.2
  textplate-small-plastic: 1
  aai-warehouse-requester: 0.1
  aai-storehouse-active-provider: 0.1
  textplate-large-glass: 1
  aai-warehouse-active-provider: 0.02
  logistic-chest-storage: 2
  textplate-small-steel: 1
  textplate-small-iron: 1
  aai-warehouse-storage: 0.1
  textplate-small-gold: 1
  logistic-chest-passive-provider: 5
  construction-robot: 10
  cargo-wagon: 1
  gate: 1
  decider-combinator: 5
  jetpack-3: 0.001
  se-energy-beam-defence: 0.001
  chemical-plant: 1
  fast-inserter: 10
  filter-inserter: 10
  long-handed-inserter: 5
  stack-inserter: 2
  pumpjack: 0.1
  se-space-assembling-machine: 5
  se-beryllium-plate: 200
  effectivity-module-3: 1
  discharge-defense-remote: 0.001
  destroyer-capsule: 0.1
  pump: 20
  programmable-speaker: 0.01
  se-pylon-substation: 0.5
  train-stop: 1
  se-delivery-cannon-weapon: 0.01
  power-armor-mk2: 0.0001
  fuel-processor: 0.5
  se-condenser-turbine: 0.25
  solar-panel: 500
  locomotive: 0.25
  battery-mk2-equipment: 0.1
  oil-refinery: 0.5
  submachine-gun: 0.001
  se-pylon-construction: 1
  se-electric-boiler: 0.5
  se-spaceship-clamp: 0.01
  lab: 0.01
  area-mining-drill: 2
  electric-mining-drill: 4
  # se-holmium-plate: 100
  substation: 5
  se-recycling-facility: 0.05
  arithmetic-combinator: 5
  se-meteor-defence: 0.02
  poison-capsule: 2
  se-addon-power-pole: 10
  productivity-module: 8
  uranium-rounds-magazine: 15
  roboport: 1
  se-supercharger: 0.05
  discharge-defense-equipment: 0.001
  se-space-probe-rocket-silo: 0.0001
  rail-chain-signal: 10
  belt-immunity-equipment: 0.001
  uranium-fuel-cell: 20
  se-meteor-point-defence: 1
  rocket-launcher: 0.01
  artillery-targeting-remote: 0.01
  green-wire: 100
  atomic-bomb: 1
  nuclear-reactor: 0.02
  heavy-oil-barrel: 10
  cluster-grenade: 1.5
  ironclad: 0.001
  slowdown-capsule: 5
  se-spaceship-gate: 1
  se-lifesupport-facility: 0.01
  night-vision-equipment: 0.0001
  # se-space-capsule: 0.1 This has too many bussed ingredients and I'm not sure how best to handle that yet
  pipe: 25
  car: 0.001
  fluid-wagon: 0.5
  aai-signal-sender: 0.1
  exoskeleton-equipment: 0.01
  red-wire: 100
  se-thruster-suit: 0.0001
  express-underground-belt: 50
  spidertron-remote: 1
  se-canister: 50
  artillery-turret: 0.5
  assembling-machine-3: 5
  repair-pack: 10
  speed-module-3: 1
  gun-turret: 1
  personal-roboport-mk2-equipment: 0.001
  se-spaceship-wall: 4
  se-rocket-launch-pad: 0.05
  offshore-pump: 1
  se-spaceship-floor: 16
  storage-tank: 1
  explosive-rocket: 10
  se-pylon: 5
  power-switch: 0.01
  electric-furnace: 2
  land-mine: 100
  se-delivery-cannon: 1
  se-delivery-cannon-capsule: 2
  laser-turret: 8
  effectivity-module: 8
  express-transport-belt: 200
  rail: 50
  constant-combinator: 5
  cliff-explosives: 2
  big-electric-pole: 10
  pipe-to-ground: 8
  industrial-furnace: 1
  se-fuel-refinery: 0.1
  explosive-uranium-cannon-shell: 20
  steel-wall: 20
  se-casting-machine: 4
  se-rtg-equipment: 0.001
  tank: 0.001
  accumulator: 500
  se-space-elevator: 0.001
  aai-signal-receiver: 0.05
  se-delivery-cannon-weapon-capsule: 1
  mortar-cluster-bomb: 1
  beacon: 1
  small-lamp: 5
  logistic-robot: 50
  se-meteor-point-defence-ammo: 5
  medium-electric-pole: 10
  centrifuge: 0.1
  heat-exchanger: 1
  rail-signal: 10
  express-splitter: 50
  flamethrower-turret: 1
  personal-laser-defense-equipment: 0.001
  se-core-miner: 0.05
  se-pulveriser: 1
peak-outputs:
  steam-turbine: 3
  heat-pipe: 25
  nuclear-fuel: 5
  se-medpack-2: 10
  artillery-wagon: 2
  se-spaceship-ion-booster-tank: 1
  se-rocket-landing-pad: 1
  stack-filter-inserter: 20
  iron-chest: 50
  steel-chest: 12
  hazard-concrete: 200
  refined-hazard-concrete: 200
  se-delivery-cannon-chest: 5
  construction-robot: 200
  cargo-wagon: 2
  gate: 10
  se-energy-beam-defence: 0.1
  chemical-plant: 20
  filter-inserter: 50
  long-handed-inserter: 50
  stack-inserter: 50
  pumpjack: 5
  se-space-assembling-machine: 50
  pump: 20
  train-stop: 5
  se-condenser-turbine: 4
  locomotive: 5
  oil-refinery: 5
  se-electric-boiler: 1
  se-spaceship-clamp: 1
  area-mining-drill: 10
  electric-mining-drill: 40
  substation: 10
  se-recycling-facility: 1
  se-meteor-defence: 1
  se-addon-power-pole: 1
  uranium-rounds-magazine: 300
  destroyer-capsule: 9
  roboport: 5
  rail-chain-signal: 20
  uranium-fuel-cell: 20
  se-meteor-point-defence: 10
  rocket-launcher: 0.4
  green-wire: 20
  atomic-bomb: 1
  nuclear-reactor: 0.25
  cluster-grenade: 20
  ironclad: 0.1
  se-spaceship-gate: 1
  se-space-capsule: 0.1
  pipe: 100
  car: 0.1
  fluid-wagon: 2
  aai-signal-sender: 0.1
  exoskeleton-equipment: 0.4
  red-wire: 20
  spidertron-remote: 0.1
  artillery-turret: 2
  assembling-machine-3: 25
  repair-pack: 20
  gun-turret: 4
  se-spaceship-wall: 10
  se-rocket-launch-pad: 0.2
  offshore-pump: 2
  se-spaceship-floor: 75
  storage-tank: 4
  explosive-rocket: 80
  se-pylon: 10
  se-pylon-substation: 5
  se-pylon-construction: 10
  electric-furnace: 24
  land-mine: 60
  se-delivery-cannon: 4
  se-delivery-cannon-capsule: 10
  laser-turret: 20
  effectivity-module: 8
  rail: 500
  cliff-explosives: 20
  big-electric-pole: 10
  pipe-to-ground: 100
  industrial-furnace: 6
  se-fuel-refinery: 4
  explosive-uranium-cannon-shell: 40
  steel-wall: 100
  se-casting-machine: 20
  se-rtg-equipment: 0.8
  tank: 0.1
  se-space-elevator: 0.2
  aai-signal-receiver: 0.5
  se-delivery-cannon-weapon-capsule: 10
  mortar-cluster-bomb: 15
  beacon: 10
  small-lamp: 50
  logistic-robot: 400
  se-meteor-point-defence-ammo: 100
  medium-electric-pole: 50
  centrifuge: 4
  heat-exchanger: 10
  rail-signal: 100
  flamethrower-turret: 10
  se-core-miner: 1
  se-pulveriser: 5
